# permissions for end users to edit oidcproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oidcprovider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: authelia-oidc-operator
    app.kubernetes.io/part-of: authelia-oidc-operator
    app.kubernetes.io/managed-by: kustomize
  name: oidcprovider-editor-role
rules:
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcproviders/status
  verbs:
  - get
