# permissions for end users to view oidcproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidcprovider-viewer-role
rules:
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcproviders/status
  verbs:
  - get
