# permissions for end users to view oidcclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oidcclient-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: authelia-oidc-operator
    app.kubernetes.io/part-of: authelia-oidc-operator
    app.kubernetes.io/managed-by: kustomize
  name: oidcclient-viewer-role
rules:
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcclients/status
  verbs:
  - get
