# permissions for end users to view oidcproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oidcprovider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: authelia-oidc-operator
    app.kubernetes.io/part-of: authelia-oidc-operator
    app.kubernetes.io/managed-by: kustomize
  name: oidcprovider-viewer-role
rules:
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authelia.milas.dev
  resources:
  - oidcproviders/status
  verbs:
  - get
