apiVersion: authelia.milas.dev/v1alpha1
kind: OIDCProvider
metadata:
  name: oidcprovider-sample
spec:
  cors:
    endpoints:
      - authorization
      - token
      - revocation
      - introspection
    allowed_origins:
      - https://example.com
