apiVersion: authelia.milas.dev/v1alpha2
kind: OIDCClient
metadata:
  labels:
    app.kubernetes.io/name: oidcclient
    app.kubernetes.io/instance: oidcclient-sample
    app.kubernetes.io/part-of: authelia-oidc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: authelia-oidc-operator
  name: oidcclient-sample
spec:
  # TODO(user): Add fields here
